- source/irfs/background/index.rst
- source/irfs/effective_area/index.rst
- source/irfs/energy_dispersion/index.rst
- source/irfs/index.rst
- source/irfs/psf/psf_3gauss/index.rst
- source/irfs/psf/psf_king/index.rst
- source/irfs/psf/psf_table/index.rst
This pull request specifies the IRF axis orders.
It became apparent that this is needed because we accidentally chose an `ENERGY, THETA` order for `BKG_2D`, whereas the current AEFF and PSF formats use `THETA, ENERGY` (see https://github.com/gammapy/gammapy/pull/461#issuecomment-188125729).
I think this pull request is uncontroversial and I'll merge it later today.
Still, @jknodlseder, @mimayer, @JouvinLea, if you could have a look and specifically comment on these questions, that would be useful:
- OK to use `THETA, ENERGY` axis order everywhere? Or is `ENERGY, THETA` better? The main difference is memory access speed ... values that are typically accessed together should be consecutive in memory so that CPU cache performance is better. I haven't thought about  / benchmarked what is …
> Specify IRF axis orders

- source/events/index.rst
This PR updates the spec of the `EVENT_ID` field for DL3 event lists.
There was already some discussion on this in #15 and (I think) agreement that `BUNCH_ID` should not be in the DL3 event list spec (see  https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/15#issuecomment-163665721).
@mimayer @jknodlseder @cboisson @kosack - Please comment.
> Update spec of EVENT_ID in DL3 event list

- source/results/binned_likelihoods/index.rst
- source/results/binned_likelihoods/tscube_hdus.csv
- source/results/index.rst
This is a first draft of the bin-by-bin likelihood format that we discussed back at the time of the PyGamma meeting.  Along with the 2D likelihood format I've also included the format that is currently output by *gttscube* -- a new ballistic tool that we recently made available in an internal ST release (11-00-00).  gttscube extends the concept of the bin-by-bin likelihood to 4 dimensions by performing an SED analysis at every spatial bin in the ROI.
> Binned Likelihood Formats

- source/data_storage/obs_index/index.rst
This PR adds an integer code of `-1` for unknown data quality for the observation index files.
> Add int code for unknown data quality

- source/irfs/psf/psf_table/index.rst
This PR changes the PSF table units from `deg^-2` to `sr^-1` as suggested by @jknodlseder in #54.
I think there is agreement on this change, merging this now.
If someone comes across this later and disagrees, please comment in #54 or open a new issue or pull request.
> Change units of table PSF to sr^-1

- source/irfs/psf/psf_table/index.rst
This PR changes the recommended table PSF axis order to ``ENERGY``, ``THETA``, ``RAD``,
as suggested by @jknodlseder  in #56.
I'm merging this now.
> Change axis order in table PSF format

- source/data_storage/obs_index/index.rst
- source/events/events.rst
This pull request addresses #27 and adds optional columns for Galactic coordinates to the EVENTS and observation index spec. 
Merging this now.
> Add Galactic coordinates as optional columns to EVENTS and OBS_IDX

- source/events/events.rst
This PR makes the DETX / DETY columns in the EVENTS table optional.
This was the conclusion of the discussion in #15 (where no-one implemented it) and also in the IACT DL3 telcon this week:
https://github.com/open-gamma-ray-astro/2016-04_IACT_DL3_Meeting/blob/master/notes/2016-06-07-IACT_DL3_Telcon.md#minutes
I'm trying to keep the pull requests easily readable, so will make the other agreed changes to FOV coordinates in a separate pull request.
Merging this now.
> Make DETX / DETY optional in EVENTS

- source/events/events.rst
- source/general/index.rst
- source/general/notes.rst
This PR:
- changes the event list `EVENT_ID` field from TFORM `1J` (32 bit) to `1K` (64 bit)
- adds a `source/general/notes` section and a short explanation / reference concerning FITS BINTABLE TFORM data type codes.
This change in `EVENT_ID` dtype was discussed for a long time in HESS and the IACT DL3 group.
The event list spec even has this explanation why we want / need 64-bit `EVENT_ID` for HESS:
http://gamma-astro-data-formats.readthedocs.io/en/latest/events/events.html#event-id-column
As far as I know, this change is uncontroversial by now, so I will merge this PR now.
If that is not the case, please comment here and we'll re-open the discussion on this point.
There's an issue in the HESS FITS data tracker here discussing this internally, and also a check that 64-bit event list can …
> Change EVENT_ID from 32 bit to 64 bit int

- source/results/flux_points/index.rst
While implementing support for the SED format in Gammapy (see https://github.com/gammapy/gammapy/pull/810), @adonath noticed today something.
The spec currently defines `eflux` as an integral quantity, per energy bin:
> eflux : Energy flux (integral of E times dnde) between e_min and e_max. Dimensionality: energy / ( time * area )
I missed that and had assumed that `eflux` is defined as the value commonly shown in "SED" plots, the differential quantity `(e_ref ^ 2) * dnde`.
Concretely in gamma-cat, there's this published HESS SED that was given as `(e_ref ^ 2) * dnde` in the paper, and I put the values incorrectly as `eflux = (e_ref ^ 2) * dnde`:
https://github.com/gammapy/gamma-cat/blob/1815c4f14d3e369356f0e55d7885cd4792b6b051/input/papers/2016/2016arXiv160908671H/tev-000096.ecsv
Here's …
> Add E^2 dnde to SED format?

- source/data_storage/hdu_index/index.rst
- source/general/hduclass.rst
- source/irfs/full_enclosure/background/index.rst
- source/irfs/full_enclosure/effective_area/index.rst
- source/irfs/full_enclosure/energy_dispersion/index.rst
- source/irfs/full_enclosure/psf/psf_3gauss/index.rst
- source/irfs/full_enclosure/psf/psf_gtpsf/index.rst
- source/irfs/full_enclosure/psf/psf_king/index.rst
- source/irfs/full_enclosure/psf/psf_table/index.rst
- source/irfs/point_like/index.rst
This PR reverts some of the additions of "full" that @TarekHC did in #79 .
Changing Sphinx labels breaks links to the spec from outside, e.g. from the Gammapy docs:
https://travis-ci.org/gammapy/gammapy/jobs/224927389#L2002
The "full" was added in three places:
- Sphinx labels
- Section titles
- As values in the HDU index tables.
I feel that the way the "full" was added isn't helpful, i.e. no corresponding "point" was added to the spec and then one might just as well leave the distinction up to the HDUCLAS3 keyword.
Gammapy is the only software package affected by this change, so I'm merging this now.
I'll do a few follow-up pull requests in the next days to clean up and go towards the first stable version. I'll keep the PRs small so that the diffs are easy to review.
@TarekHC - If you …
> Use "full" less where not needed (to be simpler)

- source/general/hduclass.rst
This request updates the recommended value for the HDUCLASS header keyword from "CTA" to "GADF" as already introduced e.g. [here](http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/aeff/index.html).
> Update recommended value for HDUCLASS in hduclass.rst

- source/events/events.rst
HDU header keywords may not be longer than 8 characters. I therefore propose to change EVENT_CLASS to EV_CLASS.
> Updates to EVENTS extension

- source/events/events.rst
- source/events/gti.rst
Hi @cdeil @cboisson @jknodlseder  
While exporting IACT data, we found an inconsistency with our ```TIMESYS``` keyword description and other documents.
You can see that, [for example here](http://www.cv.nrao.edu/fits/documents/standards/year2000.txt), that the TIMESYS refers to the time system (or time scale) allowing the following values:
UTC  Coordinated Universal Time; defined since 1972.
UT   Universal Time, equal to Greenwich Mean Time (GMT) since 1925;
the UTC equivalent before 1972;
see: Explanatory Supplement, p. 76.
TAI  International Atomic Time; "UTC without the leap seconds";
31 s ahead of UTC on 1997-07-01.
IAT  International Atomic Time; deprecated synonym of TAI.
ET   Ephemeris Time, the predecessor of TT; valid until 1984.
TT   Terrestrial Time, the IAU standard time scale …
> Fix TIMESYS keyword

- source/irfs/full_enclosure/bkg/index.rst
The specs for background rate aren't clear if it's per livetime or per observation time:
http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html
This needs to be clear for science tools to correctly compute predicted background counts.
@jknodlseder - How do you interpret the values in ctools?
@gernotmaier - How do you fill background in the CTA IRF FITS exporters?
> Clarify background rate per livetime or obstime

- source/data_storage/obs_index/index.rst
- source/events/events.rst
- source/events/gti.rst
- source/events/pointing.rst
- source/general/time.rst
- source/references.txt
This pull request improves and avoids duplication in the specifications of times.
The only change in format is for the observation index files, where "DATE_OBS" with an underscore was used, whereas e.g. for the events "DATE-OBS" with a minus was used. My understanding is that this was a mistake, the FITS standard and also OGIP documents I found use "DATE-OBS" with a minus. I don't think that change is controversial, we already said in #95 that we want to use the same format for the observation index file that we use for EVENTS, and also almost no-one except us likes or wants to use the obs index tables anyways (see #7)
Another place where I saw "DATE_OBS" with a minus is in the CTA 1DC files produced by ctobssim, which I've reported  at https://forge.in2p3.fr/boards/243/topics/2427 (cc …
> Improve and de-duplicate time specifications

- source/irfs/irf_components/index.rst
This PR fixes a typo and explicitly states the normalisation requirements for the energy dispersion and PSF IRFs.
> Clarify normalisation of IRFs

- source/events/events.rst
- source/events/pointing.rst
- source/general/coordinates.rst
@jknodlseder @kosack all - How should we store observatory location in the FITS header?
What we mention currently is `GEOLON`, `GEOLAT` and `GEOALT` in the `POINTING` spec:
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/blame/48988405270a433a89ec6de19c1f4bc0db4bc417/source/events/pointing.rst#L46
For the `EVENTS`, in HESS and for the CTA 1DC files we use `GEOLON`, `GEOLAT` and `ALTITUDE`, e.g. for HESS:
```
GEOLAT  = -23.2717777777778 / latitude of observatory (deg)
GEOLON  = 16.5002222222222 / longitude of observatory (deg)
ALTITUDE=            1835. / altitude of observatory (m)
```
Our spec says nothing what to put for `EVENTS`, but I think we should be consistent with `POINTING`.
The [FITS standard](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa.pdf) only …
> Observatory location keys for headers

- source/events/events.rst
- source/general/coordinates.rst
- source/irfs/full_enclosure/bkg/index.rst
- source/irfs/full_enclosure/edisp/index.rst
- source/irfs/full_enclosure/psf/psf_3gauss/index.rst
- source/irfs/full_enclosure/psf/psf_king/index.rst
- source/irfs/full_enclosure/psf/psf_table/index.rst
- source/irfs/irf_axes/index.rst
The spec for field of view coordinates still needs to be written:
http://gamma-astro-data-formats.readthedocs.org/en/latest/info/coordinates.html#field-of-view
Also, I've started to write up recommended names for IRF coordinate axes:
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/index.html#irf-axes
This info should probably be moved onto the coordinates page.
The hardest part is to describe / fix the FOV coordinates and names.
I'll make a proposal in the next few days and then we can discuss ...
> Field of view coordinates and IRF axis names

- CONTRIBUTING.md
- source/general/about.rst
This PR moves the "how to contribute" info from the About page in the spec to a separate `CONTRIBUTING.md` that only appears on Github.
I think that's better than having the technical info e.g. how to install and run Sphinx be part of the spec document.
> Move contributing info to CONTRIBUTING.md

- source/index.rst
- source/lightcurves/index.rst
This PR adds a minimal description / spec for lightcurves, based on the discussion in  #61 .
I'm not a lightcurve person and don't have more time to spend on this, so this is my way of finishing up the old discussion / pull request.
Note that the description ends with a sentence that it's very preliminary. I hope that someone with an interest for this does write a better description and adds example files, and maybe even extends the likelihood profiles to include times and support light curves.
> Add first lightcurve spec

- source/events/events.rst
- source/events/gti.rst
This PR changes the notation for `dtype` in the EVENTS and GTI spec from the FITS `tform` to a `type` of just float or int, and float64 for times.
This achieves consistency with all other specs we have, where dtypes are written that way.
IMO it's also more readable, pretty much no-one knows the cryptic FITS type codes by heart.
Also it couples the spec less tighly to FITS, e.g. if someone wants to use HDF5 or ECSV to store some data using this format, that works just fine.
Note that we still have the notes how to look up the FITS type codes if someone needs those (e.g. when writing code that uses CFITSIO directly?):
https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/blob/master/source/general/notes.rst
> Uniform dtype in spec (tform -> type)

- source/about.rst
- source/general/notes.rst
- source/references.txt
The about and how to contribute page should be updated:
http://gamma-astro-data-formats.readthedocs.org/en/latest/info/about.html
Add link to https://lists.nasa.gov/mailman/listinfo/open-gamma-ray-astro
and explain that high-level discussion should go there, detailed discussion in Github issues.
Also, there's people that want to read a PDF and send feedback on that and not use Github,
so we have to point out where to get the latest stable and master PDF version and where to send the comments.
> Update about and how to contribute page

- source/events/events.rst
The current EVENTS spec has a ton of required header keys:
https://gamma-astro-data-formats.readthedocs.io/en/latest/events/events.html#mandatory-header-keywords
This PR moves the following keys from required to optional:
* ORIGIN
* CREATOR
* TELESCOP
* INSTRUME
* OBSERVER
* OBJECT
* OBS_MODE
* EV_CLASS
* TELAPSE
`TELAPSE` is superfluous, it's defined as `TSTOP - START` which are required. So IMO should be optional.
All of the others are "provenance" information, not used by the science tools.
As far as I can see, all of them are problematic and not well defined.
There is no agreement on observing mode values to use, or how to put event classes or what OBJECT to put for survey operations, or what OBSERVER to put when simulating CTA data now.
So making those keys required when it's not …
> Move EVENTS header keys from required to optional

- source/about.rst
- source/data_storage/hdu_index/index.rst
This PR improves the HDU index table spec.
This was triggered by https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/118 - I've decided to keep the HDU index table as-is. It's not possible to make it compatible with the HDUCLAS header keys, without braking backward-compatibility completely or making the index table very complex. These index tables have been used and are in use since 3 or 4 years. They will likely be completly replaced by something better within the next year or two. I've added a section at the end of the page explaining the differences to HDUCLAS.
One open TODO in the spec was the use of BASE_DIR. I have clarified this in the spec here, and improved the implementation in Gammapy to make this work properly in https://github.com/gammapy/gammapy/pull/1585 …
> Improve HDU index table spec

- source/events/events.rst
- source/events/gti.rst
- source/events/pointing.rst
- source/irfs/full_enclosure/aeff/index.rst
- source/irfs/full_enclosure/bkg/index.rst
- source/irfs/full_enclosure/edisp/index.rst
- source/irfs/full_enclosure/psf/psf_3gauss/index.rst
- source/irfs/full_enclosure/psf/psf_gtpsf/index.rst
- source/irfs/full_enclosure/psf/psf_king/index.rst
- source/irfs/full_enclosure/psf/psf_table/index.rst
- source/irfs/irf_components/index.rst
- source/irfs/point_like/index.rst
- source/skymaps/healpix/index.rst
- source/spectra/ogip/index.rst
This PR is to address #118 . It consistently puts upper-case strings in the page or section headings, to be consistent with the HDUCLAS keys. Note that this is a cosmetic change, it does not imply any change in the data formats.
> Use upper-case in HDU description headings

- source/data_storage/hdu_index/index.rst
- source/data_storage/index.rst
- source/data_storage/obs_index/index.rst
This PR changes the observation index spec, moving some columns from required to optional.
Now only OBS_ID, pointing position and start / stop time are required. That's what's used 90% or more of the time do to obs selection.
All of the other keys are sometimes used, but which ones depends, and having them all as required causes problems, because then to have a valid file people often have to make up information that doesn't exist. E.g. object is not available for scan observations. E.g. TELLIST is information I didn't have when making the CTA DC1 index tables. 
This is now in line with other parts of the spec (e.g. the EVENTS), where also only things that are really required to be functionatl are listed in the required section.
> Update observation index table spec

- source/events/events.rst
This PR adds back RA_PNT and DEC_PNT as required header keys in EVENTS .
They were initially in, but then removed already in 2016 in #39 .
There was a lot of discussion on that point there, and I think in the end there was agreement that as long as POINTING isn't used much, those header keys should remain, and it was my oversight that they got lost.
@jknodlseder - OK?
@mackaiver - Please add those header keys for your FACT DL3 FITS writer. I think otherwise your data will not work with ctools, and will stop working with Gammapy soon when we change from accessing that info from the obs index files to accessing it from the EVENTS header.
> Add RA_PNT and DEC_PNT as required header keys in EVENTS

- source/general/coordinates.rst
- source/irfs/full_enclosure/bkg/index.rst
This PR introduces a new header keyword useful for field-of-view coordinates. Since there are two definitions in use, namely an Alt/Az-aligned system with
`DETX = FOV_ALTAZ_LON`
`DETY = FOV_ALTAZ_LAT`
and a RA/Dec-aligned system with
`DETX = FOV_RADEC_LON`
`DETY = FOV_RADEC_LAT`,
the new header keyword can be used to specify which definition was used in the construction of a 3D background model.
Note that this PR only proposed to add this keyword for the background IRF, not the EVENTS file (since it's unclear whether field-of-view coordinates should be listed there at all).
> Add FOVALIGN header keyword for background

- source/general/fits-arrays.rst
- source/general/time.rst
- source/references.txt
Updates the time definition keywords to how they are defined in the current FITS standard 4.0.
Basically merges `DATE-*` and `TIME-*` into `DATE-*` with a full ISO8601 date and time string
> Time updates

- source/index.rst
Add a link to the latest release version, instead of a link to the page itself.
> Add link to latest release version to index

- source/events/events.rst
Shamelessly copying from what @maxnoe has just suggested in issue #34, a PR adding the optional `gammaness` column.
@maxnoe, from your suggestion I have replaced "this shower was induced by a gamma ray" with "the event was produced by a gamma ray", if we have to include gamma-ray satellites - though one can argue that what develops in a pair-conversion satellite is indeed a shower. But I thought it would be better to keep it more general.
> Added optional gammaness column in EVENTS hdu

- source/data_storage/hdu_index/index.rst
The rad max tables were missing from the HDU index table description.
> Add rad max to possible HDU index values

- source/data_storage/index.rst
- source/events/events.rst
- source/events/index.rst
- source/irfs/index.rst
Hi all,
As we discussed in the issue #167, I've made some small changes to make the format inclusive to wide-field instruments, such as HAWC.
- I've removed the word IACT from every section title and replaced it by "gamma-ray instrument" whenever was possible for some instances in the main text. The result is still pretty IACT-centric, but at least is a little better now :smile: 
- The headers `RA_PNT`, `DEC_PNT` in the event lists are now optional, and instead, `AZ_PNT` and `ALT_PNT` are mandatory, which keeps the pointing information in the mandatory headers, while allowing wide-field  instruments to set these to some fixed value (zenith) and remain compatible.
For this last point, however, it is important to distinguish what type of purpose would this pointing information be used for. …
> Make RA/Dec pointing optional to include wide-field ground array instruments

- source/skymaps/index.rst
This PR adds a small addition to support additional keywords for time based map axes, based on the same time format standards used elsewhere in GADF.
> Add support for time keywords for sky map axes

- source/data_storage/obs_index/index.rst
Following #168 and the discussion in #167, this PR adds the `OBS_MODE` column as mandatory in the observation index table. Similarly, the mandatory pointing columns are no longer just `RA_PNT` and `DEC_PNT`, but `AZ_PNT` and `ALT_PNT` when the observation mode is `DRIFT`.
> Add OBS_MODE to the observation index table

- source/events/events.rst
There was some confusion regarding OBS_MODE in LST in the current dev version, has the OGIP defined values only talk about satellites.
I added a note that most IACT data should use POINTING, indiciating constant equatorial values for the observation.
> Add sentence about OBS_MODE for IACTs
